<?php namespace AbyssalArts\SteamApi\Controllers;

class MicrotransactionController extends \Controller {

	public function StartMicrotransaction()
	{
		$microtxn = \Steam::microtransaction(true);

		//Parameters
		$orderId = 1; //generated by the system
		$appId = \Config::get('steam-api::appId');
		$steamId = \Input::get('steamid');

		$items_raw = \Input::get('items');
		//Convert the items list to JSON
		$items_json = json_decode($items_raw);
		//Convert the items Json to an item object
		$item = new \Item((object)['itemid'=>$items_json->{'itemid'}, 'qty'=>$items_json->{'qty'}, 'amount'=>$items_json->{'amount'}, 'description'=>$items_json->{'description'}, 'category'=>$items_json->{'category'});
		//add each item to the items list
		$items = new \Collection();
		$items->add($item);

		$itemCount = $items->count();


		$language = \Input::get('language');
		$currency = \Input::get('currency');
		
		//Call ISteamMicroTxn/InitTxn
		
		$response = $microtxn->InitTxn($orderId, $steamId, $appId, $itemCount, $language, $currency, $items);
		
		//Output
		if ($response->result == 'OK')
		{
			//success
			return json_decode($response);
		}
		else
		{
			//failure
			return $response->error->errorcode . ": " . $response->error->errordesc;
		}
	}
}