<?php namespace AbyssalArts\SteamApi\Controllers;

class MicrotransactionController extends \Controller {

	public function StartMicrotransaction()
	{
		$microtxn = \Steam::microtransaction(true);

		//Parameters
		$orderId = 1; //generated by the system
		$appId = \Config::get('steam-api::appId');
		$steamId = \Input::get('steamid');
		$items = \Input::get('items');
		$itemCount = $items->count();
		$language = \Input::get('language');
		$currency = \Input::get('currency');
		
		//Call ISteamMicroTxn/InitTxn
		
		$response = $microtxn->InitTxn($orderId, $steamId, $appId, $itemCount, $language, $currency, $items);
		
		//Output
		if ($response->result == 'OK')
		{
			//success
			return json_decode($response);
		}
		else
		{
			//failure
			return $response->error->errorcode . ": " . $response->error->errordesc;
		}
	}
}